{
 "title": "Librarian2 metrics",
 "description": "Adopted dashboard for JVM metrics with OpenTelemetry instrumentation based on service_name",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java",
  "otel",
  "opentelemetry",
  "otlp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": {
     "query": "label_values({__name__=~\"jvm_class_count|process_runtime_jvm_classes_current_loaded|jvm_classes_loaded\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "HTTP server request rate",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_seconds_count|http_server_duration_count|http_server_duration_milliseconds_count|http_server_requests_milliseconds_count|http_server_requests_count|http_server_requests_seconds_count\", service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "HTTP server error ratio - ratio of requests that return 5xx",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (service_name)(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\", service_name=~\"$service_name\", http_response_status_code=~\"5.*\"}[$__rate_interval]))) / on (service_name) (sum by (service_name)(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\", service_name=~\"$service_name\"}[$__rate_interval])))\nor\n(sum by (service_name)(rate({__name__=~\"http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", service_name=~\"$service_name\", http_status_code=~\"5.*\"}[$__rate_interval]))) / on (service_name) (sum by (service_name)(rate({__name__=~\"http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", service_name=~\"$service_name\"}[$__rate_interval])))\nor\n(sum by (service_name)(rate({__name__=~\"http_server_requests_milliseconds_count|http_server_requests_count|http_server_requests_seconds_count\", service_name=~\"$service_name\", outcome=\"SERVER_ERROR\"}[$__rate_interval]))) / on (service_name) (sum by (service_name)(rate({__name__=~\"http_server_requests_milliseconds_count|http_server_requests_count|http_server_requests_seconds_count\", service_name=~\"$service_name\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (95%)",
   "type": "timeseries",
   "description": "95th percentile of HTTP server request duration in seconds",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le, service_name) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket|http_server_requests_seconds_bucket\", service_name=~\"$service_name\"}[$__rate_interval]))))\nor\n(histogram_quantile(0.95, sum by(le, service_name) (rate({__name__=~\"http_server_duration_milliseconds_bucket|http_server_requests_milliseconds_bucket|http_server_requests_bucket\", service_name=~\"$service_name\"}[$__rate_interval]))) / 1000)\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the whole system",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_cpu_recent_utilization|jvm_cpu_recent_utilization_ratio|process_runtime_jvm_system_cpu_utilization|process_runtime_jvm_system_cpu_utilization_ratio|system_cpu_usage\", service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory utilization",
   "type": "timeseries",
   "description": "Used heap memory / heap memory limit ",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (service_name) ({__name__=~\"jvm_memory_used|jvm_memory_used_bytes\",jvm_memory_type=\"heap\", service_name=~\"$service_name\"}) / on(service_name) sum by (service_name) ({__name__=~\"jvm_memory_limit|jvm_memory_limit_bytes\",jvm_memory_type=\"heap\", service_name=~\"$service_name\"}))\nor\n(sum by (service_name) ({__name__=~\"process_runtime_jvm_memory_usage|process_runtime_jvm_memory_usage_bytes\",type=\"heap\", service_name=~\"$service_name\"}) / on(service_name) sum by (service_name) ({__name__=~\"process_runtime_jvm_memory_limit|process_runtime_jvm_memory_limit_bytes\",type=\"heap\", service_name=~\"$service_name\"}))\nor\n(sum by (service_name) ({__name__=~\"jvm_memory_used|jvm_memory_used_bytes\",area=\"heap\", service_name=~\"$service_name\"}) / on(service_name) sum by (service_name) ({__name__=~\"jvm_memory_max|jvm_memory_max_bytes\",area=\"heap\", service_name=~\"$service_name\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Percentage of time spend for garbage collection pauses",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(service_name) (rate({__name__=~\"jvm_gc_duration_sum|jvm_gc_duration_seconds_sum|process_runtime_jvm_gc_duration_sum|process_runtime_jvm_gc_duration_seconds_sum|jvm_gc_pause_sum|jvm_gc_pause_seconds_sum\",service_name=~\"$service_name\"}[$__rate_interval])))\nor\n(sum by(service_name) (rate(jvm_gc_pause_milliseconds_sum{service_name=~\"$service_name\"}[$__rate_interval])) / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "description": "Number of currently loaded classes",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_class_count|process_runtime_jvm_classes_current_loaded|jvm_classes_loaded\",service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of currently executing (also called \"live\") threads",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"jvm_thread_count|process_runtime_jvm_threads_count|jvm_threads_live\",service_name=~\"$service_name\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}