apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "librarian2.fullname" . }}
  labels:
    {{- include "librarian2.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }} 
      secretName: {{ .Values.ingress.secret }}
  rules:
    - host: {{ .Values.ingress.host }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librarian2
                port:
                  number: {{ .Values.service.port }}

